version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "⚙️ dependencies"
      - "🔗 python"

  # Updates the dependencies of the GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    labels:
      - "⚙️ dependencies"
      - "🔗 github-actions"
