name: PR Labeler

on:
  pull_request:
    types: [opened]

permissions: {}

jobs:
  pre-commit-ci:
    permissions:
      contents: read # for srvaroa/labeler to read config file
      pull-requests: write # for srvaroa/labeler to add labels in PR
    runs-on: ubuntu-latest
    steps:
    - uses: srvaroa/labeler@fe4b1c73bb8abf2f14a44a6912a8b4fee835d631 # v1.12.0
      # Config file at .github/labeler.yml
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
